// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHvOgqdrgLFaAYDSS8BdknKGiBoXy5qg',
    appId: '1:429733852625:web:50f81fa46ed3a93d765cf0',
    messagingSenderId: '429733852625',
    projectId: 'adoptapokemon4ite',
    authDomain: 'adoptapokemon4ite.firebaseapp.com',
    storageBucket: 'adoptapokemon4ite.firebasestorage.app',
    measurementId: 'G-GH6X2YJVX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDbejN9fi7D7WwJ2vwLEeLbnu0MNTfRv8',
    appId: '1:429733852625:android:80b72458376a8b8b765cf0',
    messagingSenderId: '429733852625',
    projectId: 'adoptapokemon4ite',
    storageBucket: 'adoptapokemon4ite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5G-MezoGvcyopbyx5u4ObVz1XvY6wZDE',
    appId: '1:429733852625:ios:eb1117bd2f4c9600765cf0',
    messagingSenderId: '429733852625',
    projectId: 'adoptapokemon4ite',
    storageBucket: 'adoptapokemon4ite.firebasestorage.app',
    iosBundleId: 'com.example.quizOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5G-MezoGvcyopbyx5u4ObVz1XvY6wZDE',
    appId: '1:429733852625:ios:eb1117bd2f4c9600765cf0',
    messagingSenderId: '429733852625',
    projectId: 'adoptapokemon4ite',
    storageBucket: 'adoptapokemon4ite.firebasestorage.app',
    iosBundleId: 'com.example.quizOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaHvOgqdrgLFaAYDSS8BdknKGiBoXy5qg',
    appId: '1:429733852625:web:5b4def82aa866155765cf0',
    messagingSenderId: '429733852625',
    projectId: 'adoptapokemon4ite',
    authDomain: 'adoptapokemon4ite.firebaseapp.com',
    storageBucket: 'adoptapokemon4ite.firebasestorage.app',
    measurementId: 'G-J3CEX6B6CS',
  );

}